API_key = "TwitterAPI_key"
API_key_Secret = "TwitterAPI_key_Secret"
Access_Token = "TwitterAccess_Token"
Access_Token_Secret = "TwitterAccess_Token_Secret"
Bearer_Token = "TwitterBearer_Token"
api_url='https://notify-api.line.me/api/notify'
search_url="https://api.twitter.com/2/tweets/search/recent"
server='LINE notify トークン'
sleeptime_min_hour=1
sleeptime_min_minute=0
sleeptime_min_second=0
sleeptime_max_hour=5
sleeptime_max_minute=59
sleeptime_max_second=59
path = r"臨時保存先(C:\\Users...)"
pathtxt = r"臨時保存先(C:\\Users...)"
datas_path=r".."
